# Generated by Django 4.1 on 2022-08-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asosiy', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umumiy', models.PositiveSmallIntegerField()),
                ('tolandi', models.PositiveSmallIntegerField()),
                ('miqdor', models.PositiveSmallIntegerField()),
                ('nasiya', models.PositiveSmallIntegerField()),
                ('sana', models.DateField(auto_now_add=True)),
                ('foyda', models.PositiveSmallIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.client')),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiy.maxsulot')),
                ('ombor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ombor')),
            ],
        ),
    ]
